#开发环境配置
server:
#默认端口号8080
port:1001
servlet:
#应用访问路径
context-path: /


tomcat:
#tomcat的URI编码
uri-encoding:UTF-8;
#tomcat最大线程数，默认为200
max-threads:800
#tomcat启动初始化的线程数，默认为25
min-spare-threads:30


spring:
application:
name: ${APPLICATION_NAME:sal-local}

